
// File generated by Wsutil Compiler version 1.0092 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by WsUtil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from an XSD file, the file contains definition of 
// C/C++ structures types that correspond to types defined in the XSD file. 
// For example, if the following XSD complexType is defined in the XSD file
//
//      <xsd:complexType name="AddRequest">
//          <xsd:sequence>
//              <xsd:element minOccurs="0" name="a" type="xsd:int" />
//              <xsd:element minOccurs="0" name="b" type="xsd:int" />
//          </xsd:sequence>
//      </xsd:complexType>
// 
// this file contains the following definitions of the structure 
//      // AddRequest (xsd:complexType)
//      // <AddRequest xmlns='http://tempuri.org'>
//      // WS_STRUCT_DESCRIPTION* = &calculator_xsd.globalTypes.AddRequest
//      struct AddRequest
//      {
//          int a;
//          int b;
//      };
//
// For more information on how to use the C/C++ types generated in this file to read or write elements of XML documents that conform to 
// this XSD, please see the documentation for 
// WsReadType() and WsWriteType() functions.
// 
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following types were generated:

//     struct _Login;
//     struct _LoginResponse;
//     struct _Score;
//     struct _ScoreResponse;
//     struct _ListLevels;
//     struct _ListLevelsResponse;
//     struct _LoadLevel;
//     struct _LoadLevelResponse;
//     struct _getTexturesList;
//     struct _getTexturesListResponse;
//     struct _downloadTexture;
//     struct _downloadTextureResponse;
//     struct _getSoundsList;
//     struct _getSoundsListResponse;
//     struct _downloadSound;
//     struct _downloadSoundResponse;
//     struct _uploadRoute;
//     struct _uploadRouteResponse;
//     struct _getEnemiesModelsList;
//     struct _getEnemiesModelsListResponse;
//     struct _downloadEnemiesModels;
//     struct _downloadEnemiesModelsResponse;

// The following header files must be included in this order before this one

// #include <WebServices.h>

////////////////////////////////////////////////
// C structure definitions for generated types
////////////////////////////////////////////////

// typeDescription: n/a
typedef struct _Login 
{
    WCHAR* username; // optional
    WCHAR* password; // optional
} _Login;

// typeDescription: n/a
typedef struct _LoginResponse 
{
    int LoginResult;
} _LoginResponse;

// typeDescription: n/a
typedef struct _Score 
{
    WCHAR* username; // optional
    WCHAR* levelName; // optional
    int score;
} _Score;

typedef struct _ScoreResponse _ScoreResponse;

typedef struct _ListLevels _ListLevels;

// typeDescription: n/a
typedef struct _ListLevelsResponse 
{
    WCHAR* ListLevelsResult; // optional
} _ListLevelsResponse;

// typeDescription: n/a
typedef struct _LoadLevel 
{
    WCHAR* levelName; // optional
} _LoadLevel;

// typeDescription: n/a
typedef struct _LoadLevelResponse 
{
    WCHAR* LoadLevelResult; // optional
} _LoadLevelResponse;

typedef struct _getTexturesList _getTexturesList;

// typeDescription: n/a
typedef struct _getTexturesListResponse 
{
    WCHAR* getTexturesListResult; // optional
} _getTexturesListResponse;

// typeDescription: n/a
typedef struct _downloadTexture 
{
    WCHAR* textureName; // optional
} _downloadTexture;

// typeDescription: n/a
typedef struct _downloadTextureResponse 
{
    WCHAR* downloadTextureResult; // optional
} _downloadTextureResponse;

typedef struct _getSoundsList _getSoundsList;

// typeDescription: n/a
typedef struct _getSoundsListResponse 
{
    WCHAR* getSoundsListResult; // optional
} _getSoundsListResponse;

// typeDescription: n/a
typedef struct _downloadSound 
{
    WCHAR* soundName; // optional
} _downloadSound;

// typeDescription: n/a
typedef struct _downloadSoundResponse 
{
    WCHAR* downloadSoundResult; // optional
} _downloadSoundResponse;

// typeDescription: n/a
typedef struct _uploadRoute 
{
    WCHAR* username; // optional
    WCHAR* level; // optional
    WCHAR* route; // optional
} _uploadRoute;

typedef struct _uploadRouteResponse _uploadRouteResponse;

typedef struct _getEnemiesModelsList _getEnemiesModelsList;

// typeDescription: n/a
typedef struct _getEnemiesModelsListResponse 
{
    WCHAR* getEnemiesModelsListResult; // optional
} _getEnemiesModelsListResponse;

// typeDescription: n/a
typedef struct _downloadEnemiesModels 
{
    WCHAR* modelName; // optional
} _downloadEnemiesModels;

// typeDescription: n/a
typedef struct _downloadEnemiesModelsResponse 
{
    WCHAR* downloadEnemiesModelsResult; // optional
} _downloadEnemiesModelsResponse;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _tempuri_org_xsd
{
    struct // globalElements
    {
        // xml element: Login ("http://tempuri.org/")
        // c type: _Login
        // elementDescription: tempuri_org_xsd.globalElements.Login
        WS_ELEMENT_DESCRIPTION Login;
        
        // xml element: LoginResponse ("http://tempuri.org/")
        // c type: _LoginResponse
        // elementDescription: tempuri_org_xsd.globalElements.LoginResponse
        WS_ELEMENT_DESCRIPTION LoginResponse;
        
        // xml element: Score ("http://tempuri.org/")
        // c type: _Score
        // elementDescription: tempuri_org_xsd.globalElements.Score
        WS_ELEMENT_DESCRIPTION Score;
        
        // xml element: ScoreResponse ("http://tempuri.org/")
        // c type: _ScoreResponse
        // elementDescription: tempuri_org_xsd.globalElements.ScoreResponse
        WS_ELEMENT_DESCRIPTION ScoreResponse;
        
        // xml element: ListLevels ("http://tempuri.org/")
        // c type: _ListLevels
        // elementDescription: tempuri_org_xsd.globalElements.ListLevels
        WS_ELEMENT_DESCRIPTION ListLevels;
        
        // xml element: ListLevelsResponse ("http://tempuri.org/")
        // c type: _ListLevelsResponse
        // elementDescription: tempuri_org_xsd.globalElements.ListLevelsResponse
        WS_ELEMENT_DESCRIPTION ListLevelsResponse;
        
        // xml element: LoadLevel ("http://tempuri.org/")
        // c type: _LoadLevel
        // elementDescription: tempuri_org_xsd.globalElements.LoadLevel
        WS_ELEMENT_DESCRIPTION LoadLevel;
        
        // xml element: LoadLevelResponse ("http://tempuri.org/")
        // c type: _LoadLevelResponse
        // elementDescription: tempuri_org_xsd.globalElements.LoadLevelResponse
        WS_ELEMENT_DESCRIPTION LoadLevelResponse;
        
        // xml element: getTexturesList ("http://tempuri.org/")
        // c type: _getTexturesList
        // elementDescription: tempuri_org_xsd.globalElements.getTexturesList
        WS_ELEMENT_DESCRIPTION getTexturesList;
        
        // xml element: getTexturesListResponse ("http://tempuri.org/")
        // c type: _getTexturesListResponse
        // elementDescription: tempuri_org_xsd.globalElements.getTexturesListResponse
        WS_ELEMENT_DESCRIPTION getTexturesListResponse;
        
        // xml element: downloadTexture ("http://tempuri.org/")
        // c type: _downloadTexture
        // elementDescription: tempuri_org_xsd.globalElements.downloadTexture
        WS_ELEMENT_DESCRIPTION downloadTexture;
        
        // xml element: downloadTextureResponse ("http://tempuri.org/")
        // c type: _downloadTextureResponse
        // elementDescription: tempuri_org_xsd.globalElements.downloadTextureResponse
        WS_ELEMENT_DESCRIPTION downloadTextureResponse;
        
        // xml element: getSoundsList ("http://tempuri.org/")
        // c type: _getSoundsList
        // elementDescription: tempuri_org_xsd.globalElements.getSoundsList
        WS_ELEMENT_DESCRIPTION getSoundsList;
        
        // xml element: getSoundsListResponse ("http://tempuri.org/")
        // c type: _getSoundsListResponse
        // elementDescription: tempuri_org_xsd.globalElements.getSoundsListResponse
        WS_ELEMENT_DESCRIPTION getSoundsListResponse;
        
        // xml element: downloadSound ("http://tempuri.org/")
        // c type: _downloadSound
        // elementDescription: tempuri_org_xsd.globalElements.downloadSound
        WS_ELEMENT_DESCRIPTION downloadSound;
        
        // xml element: downloadSoundResponse ("http://tempuri.org/")
        // c type: _downloadSoundResponse
        // elementDescription: tempuri_org_xsd.globalElements.downloadSoundResponse
        WS_ELEMENT_DESCRIPTION downloadSoundResponse;
        
        // xml element: uploadRoute ("http://tempuri.org/")
        // c type: _uploadRoute
        // elementDescription: tempuri_org_xsd.globalElements.uploadRoute
        WS_ELEMENT_DESCRIPTION uploadRoute;
        
        // xml element: uploadRouteResponse ("http://tempuri.org/")
        // c type: _uploadRouteResponse
        // elementDescription: tempuri_org_xsd.globalElements.uploadRouteResponse
        WS_ELEMENT_DESCRIPTION uploadRouteResponse;
        
        // xml element: getEnemiesModelsList ("http://tempuri.org/")
        // c type: _getEnemiesModelsList
        // elementDescription: tempuri_org_xsd.globalElements.getEnemiesModelsList
        WS_ELEMENT_DESCRIPTION getEnemiesModelsList;
        
        // xml element: getEnemiesModelsListResponse ("http://tempuri.org/")
        // c type: _getEnemiesModelsListResponse
        // elementDescription: tempuri_org_xsd.globalElements.getEnemiesModelsListResponse
        WS_ELEMENT_DESCRIPTION getEnemiesModelsListResponse;
        
        // xml element: downloadEnemiesModels ("http://tempuri.org/")
        // c type: _downloadEnemiesModels
        // elementDescription: tempuri_org_xsd.globalElements.downloadEnemiesModels
        WS_ELEMENT_DESCRIPTION downloadEnemiesModels;
        
        // xml element: downloadEnemiesModelsResponse ("http://tempuri.org/")
        // c type: _downloadEnemiesModelsResponse
        // elementDescription: tempuri_org_xsd.globalElements.downloadEnemiesModelsResponse
        WS_ELEMENT_DESCRIPTION downloadEnemiesModelsResponse;
        
    } globalElements;
    struct // externallyReferencedTypes
    {
        WS_STRUCT_DESCRIPTION Login;
        WS_STRUCT_DESCRIPTION LoginResponse;
        WS_STRUCT_DESCRIPTION Score;
        WS_STRUCT_DESCRIPTION ScoreResponse;
        WS_STRUCT_DESCRIPTION ListLevels;
        WS_STRUCT_DESCRIPTION ListLevelsResponse;
        WS_STRUCT_DESCRIPTION LoadLevel;
        WS_STRUCT_DESCRIPTION LoadLevelResponse;
        WS_STRUCT_DESCRIPTION getTexturesList;
        WS_STRUCT_DESCRIPTION getTexturesListResponse;
        WS_STRUCT_DESCRIPTION downloadTexture;
        WS_STRUCT_DESCRIPTION downloadTextureResponse;
        WS_STRUCT_DESCRIPTION getSoundsList;
        WS_STRUCT_DESCRIPTION getSoundsListResponse;
        WS_STRUCT_DESCRIPTION downloadSound;
        WS_STRUCT_DESCRIPTION downloadSoundResponse;
        WS_STRUCT_DESCRIPTION uploadRoute;
        WS_STRUCT_DESCRIPTION uploadRouteResponse;
        WS_STRUCT_DESCRIPTION getEnemiesModelsList;
        WS_STRUCT_DESCRIPTION getEnemiesModelsListResponse;
        WS_STRUCT_DESCRIPTION downloadEnemiesModels;
        WS_STRUCT_DESCRIPTION downloadEnemiesModelsResponse;
    } externallyReferencedTypes;
} _tempuri_org_xsd;

extern const _tempuri_org_xsd tempuri_org_xsd;

#ifdef __cplusplus
}
#endif

